- hosts: all
  become: yes
  tasks:
    - name: copy yml
      copy:
        src: /var/lib/jenkins/workspace/Odoo_testing/docker-compose.yml
        dest: /tmp
        remote_src: yes
        owner: adri
