- hosts: all
  become: yes
  tasks:
    - name: Copiamos el fichero yml
        copy:
         src: docker-compose.yml
         dest: /tmp/docker-compose.yml
         owner: root
         group: root
         mode: '0770'
    - name: Iniciar docker
      shell: docker-compose -f /tmp/docker-compose.yml up -d 
