- hosts: worker1
  become: yes
  tasks:
   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true
       
   - name: install Docker-compose
     apt:
       name: docker-compose
       state: present
       update_cache: true

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present
      - name: install APT Transport HTTPS
